channels:
- conda-forge
dependencies:
- python=3.10.16
- pip<=24.3.1
- pip:
  - mlflow==2.20.3
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - tensorflow-macos==2.15.0
  - tensorflow==2.15.0
name: mlflow-env
